    schedules:
      - tasks: '*'
        interval:
          hours: 2
    tasks:
      config:
        #manual: yes 
        priority: 1
        trakt_emit:
          username: TRAKT_USERNAME 
          account: TRAKT_ACCOUNT
          list: following
          context: watched  # You can set this to 'collected' depending on the state of your trakt info
          position: next
        accept_all: yes
        set_series_begin: yes

      auto_series:
        priority: 2
   #     disable: seen
        configure_series:
          from:
            trakt_list:
              username: TRAKT_USERNAME
              list: following
              account: TRAKT_ACCOUNT
              type: shows
              strip_dates: yes
          settings:
            identified_by: ep
            upgrade: yes
            tracking: backfill
        inputs:
          - discover:
              what:
                - emit_series: yes
              from:
                - search_rss: "http://kickass.to/tv/?rss=1"
                - torrentz: verified
                - kat:
                    category: all
                    verified: yes
                - publichd:
                    category:
                    -  BluRay 720p
                    -  BluRay 1080p 
                    -  BRRip
                - search_rss: http://showrss.info/rss.php?user_id=250602&hd=2&proper=null
        interval: 3 hour  # Search for expected episodes again every hour
        exists_series:
          - /media/STORAGE/TV Shows/
          - /media/STORAGE/Downloads/incomplete
        regexp:
          reject:
            - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} 
            - \b3-?D\b: {from: title}                             
            - \btrailer\b: {from: title}                          
            - \bR5\b: {from: title}                               
            - \bWEBSCR\b: {from: title}                           
            - \bscreener\b: {from: title}
            - \bTS\b: {from: title}
            - \bCam\b: {from: title}
            - \bRAW\b: {from: title}
            - \bSpeed.Cd\b: {from: title} #slow
            - \baac2 #no aac2 {from: title}
            - sub
            - Español
            - French
        content_filter:
          require:
            - '*.avi'
            - '*.mkv'
            - '*.mp4'
            - '*.zip'
            - '*.rar'
          reject:
            - 'password.txt'
            - '*.wmv'
            - '*.rar'
            - '*.zip'
        #seen: local
        torrent_alive: 2
        transmission:
          host: localhost
          port: 9091
          username: transmission
          password: transmission
          path: /media/STORAGE/TV Shows/{{series_name|pathscrub}}/S{{"%02d"|format(series_season)}}  
          main_file_only: yes
          content_filename: "{{ tvdb_series_name }} - {{ tvdb_season }}x{{ tvdb_episode|pad(2) }} - {{ tvdb_ep_name|default('Missing title') }}"

      fill_movie_queue:
        priority: 3
        trakt_list:
          username: TRAKT_USERNAME
          account: TRAKT_ACCOUNT
          list: watchlist
          type: movies
        seen: local
        accept_all: yes
        movie_queue: add
        interval: 3 hour

      get_movies:
        priority: 4
        content_size:
          max: 15360
          min: 512
        discover:
          what:
            - emit_movie_queue: yes
          from:
            - kat:
                category: movies
            - torrentz: good
            - publichd:
                category:
                  - BluRay 720p
                  - BluRay 1080p
                  - BRRip
        movie_queue: accept
        quality: 720p-1080p
        transmission:
          host: localhost
          port: 9091
          username: transmission
          password: transmission
          path: /media/STORAGE/Movies
        interval: 3 hour
 
#      subtitles:
#        priority: 5
#        filesystem:
#          path:
#            - /media/STORAGE/TV Shows/
#            - /media/STORAGE/Movies/
#          recursive: yes
#        accept_all: yes
#        subliminal:
#          languages:
#            - eng
#          alternatives:
#            - eng
#          exact_match: yes
#          providers: [addic7ed, opensubtitles]
#          single: no
#        interval: 30 minutes

      cleanup:
        priority: 6
        clean_transmission:
          host: localhost
          port: 9091
          username: transmission
          password: transmission
          finished_for: 12 hours
          transmission_seed_limits: yes
          enabled: yes
