version: '3'
services:
  sickrage:
    image: "tokko/sickrage:latest"
    ports:
      - "8081:8081"
    volumes:
      - /mnt/PiDrive:/root/Storage
      - /mnt/PiDrive/TV\ Shows:/media/
      - /mnt/PiDrive/settings/sickrage/:/home
    container_name: "couchpotato"
    restart: always
    container_name: "sickrage"

  couchpotato:
    image: "dtroncy/rpi-couchpotato"
    ports:
      - "5050:5050"
    volumes:
      - /mnt/PiDrive:/root/Storage
      - /mnt/PiDrive/Movies:/volumes/media
      - /mnt/PiDrive/settings/couchpotato:/volumes/data
      - /mnt/PiDrive/settings/couchpotato:/volumes/config
      - /etc/localtime:/etc/localtime:ro
    container_name: "couchpotato"
    restart: always

  deluge:
    image: "jordancrawford/rpi-deluge"
    ports:
      - "58846:58846"
      - "8112:8112"
    volumes:
      - /mnt/PiDrive/settings/deluge/config:/config
      - /mnt/PiDrive/Downloads/:/data
    container_name: "deluge"
    restart: always
